seqan/sharg-parser

include/sharg/detail/concept.hpp
include/sharg/detail/terminal.hpp
include/sharg/detail/version_check.hpp

Fixes one task of https://github.com/seqan/sharg-parser/issues/4

[MISC] Replace seqan3/core/platform -> sharg/platform.

---

include/sharg/detail/format_parse.hpp

Follow up on #28. Forgot to remove the include.

[MISC] Remove predicate.hpp from format_parse.

---

include/sharg/detail/format_base.hpp
include/sharg/detail/format_parse.hpp
include/sharg/detail/type_name_as_string.hpp
test/unit/detail/CMakeLists.txt
test/unit/detail/type_name_as_string_test.cpp

Resolves #15
~New seqan3 includes in the new test file:~
~#include <seqan3/utility/type_list/traits.hpp>~
~#include <seqan3/utility/type_list/type_list.hpp>~

[MISC] Remove dependency of seqan3::detail::type_name_as_string.

---

include/sharg/argument_parser.hpp
include/sharg/detail/format_base.hpp
include/sharg/detail/version_check.hpp
test/unit/detail/format_help_test.cpp
test/unit/detail/format_html_test.cpp
test/unit/detail/format_man_test.cpp
test/unit/detail/version_check_test.hpp
test/unit/format_parse_validators_test.cpp

Part of #31 
Prior to this PR the following has been done:
* Sharg version has also been added to the seqan_versions.txt 
https://github.com/OpenMS/usage_plots/pull/19
* Server script was changed to return the sharg version if URL is `.../SeqAn-Sharg` (instead of `SeqAn3`). See full script [here](https://gist.github.com/smehringer/13f7534ce893e05b5d16c18cfcda0297)
* Script has been updated on server in Tuebingen by @timosachsenberg (17.12.2021)
This PR does the following (by commit):
1. Changes most occurences of "seqan" to sharg
Exceptions (Open TODO): Notifications still link to seqan3 wiki page
2. Changes the URL of the server call to `SeqAn-Sharg` to get correct cookies
3. Adds small print out in test that comes in handy when manually inspecting the version tests.
4. Tiny :nail_care: …

[FEATURE] Adapt the version checker to sharg.

---

include/sharg/argument_parser.hpp
include/sharg/detail/format_help.hpp
include/sharg/validators.hpp

In all commits we don't really need the `seqan3::detail::to_string` which uses the `seqan3::debug_stream` because we only have std types and not seqan3 types.
Part of #41

[MISC] Remove some occurrences of seqan3::detail::to_string that aren't necessary.

---

include/sharg/validators.hpp

[MISC] Remove dependency on ranges::move and cpp20::back_inserter.

---

include/sharg/detail/format_parse.hpp
test/unit/format_parse_test.cpp

I did not want to bloat #43 any further but here is another removal of `seqan3::detail::to_string` that is simple as we work with std::string(views) anyway.
part of #41

[MISC] Remove seqan3::detail::to_string from format_parse.

---

CHANGELOG.md
include/sharg/argument_parser.hpp
include/sharg/validators.hpp
test/snippet/validators_input_file_ext_from_file.cpp
test/snippet/validators_input_file_ext_from_file.err
test/snippet/validators_output_file_ext_from_file.cpp
test/snippet/validators_output_file_ext_from_file.err
test/unit/format_parse_validators_test.cpp

Resolves #42 
To avoid using seqan3::io we changed the usage of the `seqan3::input_file_validator` and `seqan3::output_file_validator`, you now have to give the formats explicitly:
`sharg::input_file_validator validator{std::vector{std::string{"exe"}, std::string{"fasta"}}};` and `sharg::output_file_validator validator{sharg::output_file_open_options::create_new, std::vector{std::string{"exe"}, std::string{"fasta"}}};`.
I also created a new issue seqan/seqan3#2927 for accessing valid formats from file.

[MISC] Remove depencency of seqan3 io

---

include/sharg/detail/format_parse.hpp
include/sharg/validators.hpp

Came up when working on #41.
Simply replaces the `seqan3::arithmetic` by the metafunction `std::is_arithmetic_v`

[MISC] Remove dependency of seqan3::arithmetic by using std::is_arithmetic_v.

---

doc/tutorial/argument_parser/solution3.cpp
doc/tutorial/argument_parser/solution4.cpp
doc/tutorial/argument_parser/solution5.cpp
doc/tutorial/argument_parser/solution6.cpp
include/sharg/argument_parser.hpp
include/sharg/detail/format_help.hpp
include/sharg/validators.hpp
test/unit/format_parse_validators_test.cpp

Follow up of #44 
Most changes are euqivalent because we don't need e.g. `std::ranges::find` if we have a common range anyway. IMHO [this change](https://github.com/seqan/sharg-parser/pull/54/files#diff-4e3decd5363eace7fcffe5b6a3896159daabf014500f352ae66d10be4194991cL432) even became more readable. 
The only not nice change is this one
```diff
+    std::string str = [&range] () { std::string s; for (auto c : range) s.push_back(c); return s; }();
-    std::string str;
-    std::ranges::copy(range, std::cpp20::back_inserter(str));
```
because it is in the snippets and thus code that is exposed to the user.
We might want to think about adding the std/ranges module to the sharg parser or drop gcc-9 support which would make `#include <ranges>` available directly. Then we can change this back.

[MISC] Remove std::ranges::copy and std::cpp20::back_inserter.

---

include/sharg/auxiliary.hpp
include/sharg/concept.hpp
include/sharg/detail/format_parse.hpp

Came up when working on #41 
This replaces the need of `seqan3::input_stream_over`. Since we always use `std::istringstream` I made the concept explicit.
Name is up for discussion.

[FEATURE] Add sharg::istreamable concept.

---

include/sharg/validators.hpp
test/snippet/validators_output_file.cpp
test/snippet/validators_output_file_ext_from_file.cpp
test/snippet/validators_output_file_ext_from_file.err
test/unit/format_parse_validators_test.cpp

Open:
- We need `requires` as it's important for overload resultion.

[MISC] Add new output_file_validator ctors

---

doc/howto/custom_types/custom_type.cpp
doc/howto/custom_types/custom_type.out
doc/howto/custom_types/external_custom_type.cpp
doc/howto/custom_types/external_custom_type.out
doc/howto/custom_types/index.md
include/sharg/concept.hpp
test/documentation/DoxygenLayout.xml

After requiring ostreamable for custom types #52, we should have a proper HowTo section on it.
Fixes #41

[DOC] Add howto on custom types.

---

include/sharg/std/charconv

When sharg is backported to seqan3 and some cpp
includes sharg and seqan std/charconv, the overloads
are ambiguous. Adding explicit header guards of the
exact same name in both, resolves this.

[INFRA] Use explicit header guard to avoid ambigiutity.

---

include/sharg/argument_parser.hpp
include/sharg/validators.hpp
test/unit/format_parse_validators_test.cpp

Part of https://github.com/seqan/sharg-parser/issues/76.
In order to create a config struct, the default validator type must be independent of the option value type. This is not necessary anyway.

[MISC] Simplify the detail::default_validator.

---

include/sharg/config.hpp

[DOC] Fix missing \ingroup.

---

test/unit/detail/format_help_test.cpp

Came up when working on #113. Specifically see comment https://github.com/seqan/sharg-parser/pull/113#issuecomment-1198971397

[TEST] Remove unused version-check option and improve naming.

---

doc/setup/quickstart_cmake/index.md

Copied over from https://docs.seqan.de/seqan/3-master-user/setup.html
But all seqan3 mentions are replaced with sharg.
Directory structure of the example has also been updated.

[DOC] Include Shargs own Quick setup.

---

include/sharg/parser.hpp
test/unit/detail/format_help_test.cpp

`./my_app --version-check off`
has the same behavior as
`./my_app`
**IF** there is no required option.
If there is a required option, then an error is thrown: `required option -i is not set`
This PR fixes it. Now `./my_app --version-check off` and `./my_app` should always have the same behavior. The fix is a little indirect. The problem occurs because the `if (argc <= 1)` check that triggers the small-help-page for `./my_app` is before the `for` loop that will remove the `--version-check off` from the command line arguments of the parser. Checking it after the for loop ensures that the short-help-page is triggered regardless of the `version-check`.

[FIX] --version-check doesn't alter parser behaviour.

---

.github/workflows/ci_linux.yml
.github/workflows/ci_macos.yml
.github/workflows/ci_misc.yml
CMakeLists.txt
README.md
test/cmake/include_dependencies/generate_include_dependencies.cmake
test/cmake/sharg_require_benchmark.cmake
test/cmake/sharg_require_ccache.cmake
test/cmake/sharg_require_test.cmake
test/header/CMakeLists.txt

Since CMake 3.15.7 was released over 2.5 years ago, I think it's OK to require at least 3.15.7. This simplifies some CMake.
I'll check if we can get rid of more, but these are the low-hanging fruits.

[INFRA] Bump CMake

---

test/documentation/api-stability.js

This usually puts a API badge next to `Detailed Description`.
However,
* for actual doxygen groups, this is `no-api` if not documented
* We don't really want this for doxygen groups

[DOC] Remove API badge from groupheader

---

include/sharg/parser.hpp
test/unit/parser/format_parse_test.cpp

This extends the argument parser to also parse and provide the executable call.
It basically just forwards the `argv[0]` variable forward to the meta info part, if no explicit call was given. I would also recommend using the implicit version.

[FEAT] extend meta info by executable call

---

CHANGELOG.md
include/sharg/parser.hpp
test/unit/parser/format_parse_test.cpp

Fixes #171 
Given a parser `foo` with subcommands `bar1` and `bar2`.
```
./foo barX -h
```
will now raise an error that the subcommand was misspelled instead of printing the help page for `foo`.

[FIX] Raise an error if subcommand is misspelled and ignore trailing -h

---

include/sharg/validators.hpp

For example, `--output .` will delete the current directory when using `output_file_validator`.
`validate_writeability` is called with `.` and then tries to open `.`.
As this is a rather serious bug, I'll do Changelog/tests/reviews after merging.
Thanks to @pirovc for sacrificing his directory (which luckily contained nothing irreplaceable).

[FIX] output_file_validator deletes directories

---

include/sharg/detail/format_base.hpp
include/sharg/detail/format_help.hpp
include/sharg/parser.hpp

Exit in the `parse()` function instead of in the format itself. Arguably a better design. May also be needed for https://github.com/seqan/sharg-parser/pull/173

[MISC] Move std::exit for special formats to parser

---

include/sharg/detail/format_help.hpp
include/sharg/detail/terminal.hpp
include/sharg/detail/version_check.hpp
test/unit/detail/version_check_test.hpp

Should actually fix https://github.com/seqan/sharg-parser/pull/184, because we now only format the output, if the standard output is a terminal. Before, we checked for standard input.

[FIX] Handling of is_terminal

---

include/sharg/detail/format_base.hpp
include/sharg/detail/format_parse.hpp
include/sharg/detail/format_tdl.hpp
include/sharg/enumeration_names.hpp
include/sharg/parser.hpp

* `auto` is only allowed for non-type template parameter, e.g., `typename <size_t t>`. This is according to the Standard, gcc14 also errors: https://cdash.seqan.de/viewBuildError.php?buildid=111621
* Unified syntax `typename config_t ... config_t const & config` -> `typename validator_t ... config<validator_t> const & config`
* clang rejects the inline overloading of `std::ostream::operator<<`. Need to open the namespace.
clang still cannot deduce the template parameter for designated initialisers

[MISC] clang preparation

---

.github/workflows/ci_cmake.yml
.github/workflows/lint.yml
CHANGELOG.md
build_system/sharg-config.cmake
test/external_project/CMakeLists.txt
test/external_project/find-package-diagnostics.cmake
test/external_project/install-sharg.cmake
test/external_project/sharg_fetch_content_zip/CMakeLists.txt
test/external_project/sharg_installed/CMakeLists.txt
test/external_project/sharg_setup_tutorial/CMakeLists.txt
test/external_project/sharg_submodule_add_subdirectory/CMakeLists.txt
test/external_project/sharg_submodule_find_package/CMakeLists.txt
test/external_project/src/hello_world.cpp

Adapted from SeqAn3. Sharg 1.1.0 install is broken, because tdl/yaml-cpp is not installed correctly. As a first step, this adds tests to catch these errors.

[INFRA] Add external_project tests

---

include/sharg/detail/format_tdl.hpp
test/unit/detail/format_cwl_test.cpp

patch: using newest TDL

---

.github/workflows/ci_linux.yml
CHANGELOG.md
README.md
build_system/sharg-config.cmake
include/sharg/detail/format_base.hpp
include/sharg/detail/format_tdl.hpp
include/sharg/detail/to_string.hpp
include/sharg/parser.hpp
test/documentation/sharg_doxygen_cfg.in
test/unit/detail/format_ctd_test.cpp
test/unit/detail/format_cwl_test.cpp
test/unit/detail/format_help_test.cpp
test/unit/detail/format_html_test.cpp
test/unit/detail/format_man_test.cpp
test/unit/detail/seqan3_test.cpp
test/unit/parser/format_parse_validators_test.cpp

Tests are a bit annoying, and snippets will need to be built with tdl (readme_snippet).

[INFRA] Optional tdl

---

include/sharg/detail/format_parse.hpp
include/sharg/parser.hpp

I am pretty much making this change in all my PRs. So let's make it a separate PR :)
I will make a follow-up issue after merge with things that need to be decided once we resolved the other PRs:

[MISC] Use vector for arguments

---

test/coverage/CMakeLists.txt
test/include/sharg/test/test_fixture.hpp
test/unit/detail/format_ctd_test.cpp
test/unit/detail/format_cwl_test.cpp
test/unit/detail/format_help_test.cpp
test/unit/detail/format_html_test.cpp
test/unit/detail/format_man_test.cpp
test/unit/detail/seqan3_test.cpp
test/unit/detail/type_name_as_string_test.cpp
test/unit/detail/version_check_test.hpp
test/unit/parser/enumeration_names_test.cpp
test/unit/parser/format_parse_test.cpp
test/unit/parser/format_parse_validators_test.cpp
test/unit/parser/parser_design_error_test.cpp

This introduces `sharg::test::test_fixture` to streamline:
* constructing a parser
* constructing a parser with subcommands
* getting cout on exit (e.g., help page calls)
The aim is to make the tests easier to adept for future changes.
---
This further adds `sharg::test::early_exit_guardian`:
* Catches if something terminates the program before all tests have been run
Currently, the version_checker_test just returns in the second test, i.e. the other tests are never run.
In general, any call to `parser.parse()` that results in a special format and isn't in a `EXPECT_EXIT` context will have this problem.
The guardian checks whether `sharg::test::early_exit_guard::done()` has been called in the destructor call.
When including `sharg/test/test_fixture`, there now must be something like
``` …
```

[TEST] Use a test fixture

---

include/sharg/detail/format_base.hpp
include/sharg/parser.hpp
test/unit/detail/format_help_test.cpp
test/unit/detail/format_html_test.cpp
test/unit/parser/format_parse_test.cpp
test/unit/parser/parser_design_error_test.cpp

* Defers everything to `parse()`
* Refactors `parse()`
* Refactors `init()`
* No options/positional options allowed for subcommands (Follow-up)
* Fixes `--export-helpXhtml` being accepted for any `X`
---
Follow-up:
```cpp
sharg::parser parser{"./test_parser", {"-o", "true"}, /* update off */, {"foo"}};
parser.add_option(flag_value, sharg::config{.short_id = 'o'};
parser.parse(); // Throws because no special format + there are subcommands -> subcommand is required.
```
It's currently a `sharg::user_input_error` (`verify_subcommand()`).
I don't think it's necessary. It might be hard to differentiate between options/flags for the top-level-parser and a potentially misspelled subcommand.
¹ Can't use `std::monostate` directly because the `visit` call needs to be valid for all possible …

[MISC] Defer everything to parse()

---

test/include/sharg/test/expect_throw_msg.hpp
test/unit/parser/enumeration_names_test.cpp
test/unit/parser/format_parse_test.cpp
test/unit/parser/parser_design_error_test.cpp

This streamlines checking that a statement throws a specific error with a specific description.
Using a macro has the advantage that we get the correct traceback and can use the existing googletest code.
The incorrect description check will also print the diff (like when comparing two strings) if googletest deems it necessary to do so.
Example output for the four cases (line numbers are correct):
```
../../../../test/unit/parser/parser_design_error_test.cpp:297: Failure
Expected: parser.parse() throws an exception of type sharg::design_error.
Actual: it throws nothing.
../../../../test/unit/parser/parser_design_error_test.cpp:308: Failure
Expected: parser.add_section("") throws an exception of type sharg::user_input_error.
Actual: it throws sharg::design_error with description …
```

[TEST] Add EXPECT_THROW_MSG

---

doc/howto/subcommand_parser/subcommand_parse.cpp
doc/tutorial/parser/small_snippets.cpp

Resolves #247 
See https://github.com/doxygen/doxygen/issues/10517

[FIX,DOC] Doxygen workaround

---

doc/howto/subcommand_parser/index.md
include/sharg/parser.hpp
test/snippet/add_subcommands.cpp
test/snippet/add_subcommands.out
test/snippet/add_subcommands.out.license
test/unit/detail/format_cwl_test.cpp
test/unit/parser/subcommand_test.cpp

After 
* #238
* #239 
* #240 
* #244 
I kinda forgot about this one :)

[MISC] Allow recursive subcommands

---

CMakeLists.txt
cmake/sharg-config.cmake

CPM usually does a find_package redirect.
If `find_package` is called for some package added via CPM, it is redirected to CPM.
Before CPM 0.40.6, there was a bug that prevented this redirection from working properly.
If sharg is added via CPM, CPM will call sharg 's `CMakeLists.txt`.
Because we use `find_package` there, it is redirected and results in sharg not being available.

[FIX] Do not find_package yourself

---

.github/config/codechecker.yml
doc/tutorial/parser/solution3.cpp
doc/tutorial/parser/solution4.cpp
doc/tutorial/parser/solution5.cpp
doc/tutorial/parser/solution6.cpp
include/sharg/detail/format_base.hpp
include/sharg/detail/format_html.hpp
include/sharg/detail/format_man.hpp
include/sharg/detail/format_parse.hpp
include/sharg/detail/format_tdl.hpp
include/sharg/parser.hpp
include/sharg/std/charconv
include/sharg/validators.hpp
test/unit/detail/safe_filesystem_entry_test.cpp
test/unit/detail/version_check_test.hpp
test/unit/parser/format_parse_test.cpp
test/unit/parser/format_parse_validators_test.cpp
test/unit/std/charconv_float_test.cpp
test/unit/std/charconv_int_test.cpp

See https://docs.seqan.de/codechecker/sharg/index.html

[FIX] some codechecker reports

---

doc/howto/custom_types/custom_type.cpp
doc/howto/custom_types/external_custom_type.cpp
include/sharg/auxiliary.hpp
include/sharg/detail/format_parse.hpp
include/sharg/detail/format_tdl.hpp
include/sharg/parser.hpp
include/sharg/validators.hpp
test/include/sharg/test/test_fixture.hpp
test/snippet/custom_enumeration.cpp
test/unit/detail/format_help_test.cpp
test/unit/parser/enumeration_names_test.cpp
test/unit/parser/format_parse_test.cpp
test/unit/parser/format_parse_validators_test.cpp

https://docs.seqan.de/codechecker/sharg
After this, only shadowing stuff should remain.

[FIX] More codechecker checks

---

include/sharg/detail/format_tdl.hpp

https://gist.github.com/eseiler/c1115cc70b5847c05043ef1a9da8cfb0

[FIX] gcc15: Workaround bogus warning

---

include/sharg/detail/format_tdl.hpp

Last PR fixed some but not all cases. This one should fix all.

[FIX] gcc15: Workaround bogus warning 2nd try

---

include/sharg/detail/format_parse.hpp
include/sharg/detail/id_pair.hpp
include/sharg/parser.hpp
test/unit/parser/format_parse_test.cpp
test/unit/parser/parser_design_error_test.cpp

**To-do**
**Problem**
```cpp
sharg::parser parser{"test_parser", 5, argv, sharg::update_notifications::off};
parser.add_option(option_value, sharg::config{.short_id = 'b', .long_id = "bar"});
parser.add_option(option_value, sharg::config{.short_id = 'l', .long_id = "loo"});
parser.add_option(option_value, sharg::config{.short_id = 'f', .long_id = "foobar"});
```
When calling `./parser_test -b blah`:
```cpp
parser.is_option_set('-b'); // True
parser.is_option_set("--bar"); // False
```
This is quite unintuitive and has already caused me trouble.
A workaround is of course
```cpp
parser.is_option_set('-b') || parser.is_option_set("--bar");
```
But this relies on the user to get the short/long ID pairing correct.
**Solution**
Store short/long ID as a pair. When calling `is_option_set`, we can …

[FIX] is_option_set: match both long and short ids

---

test/api_stability/1.0.0/0001-API-FIX-Print-common-options-at-the-end-of-the-help-.patch.license
test/api_stability/1.0.0/0002-NOAPI-Update-copyright.patch.license
test/api_stability/1.0.0/0003-API-FIX-Check-app_name-at-parse.patch.license
test/api_stability/1.0.0/0004-FIX-API-tdl-support.patch.license
test/api_stability/1.1.1/0001-API-Update-TDL.patch
test/api_stability/1.1.1/0001-API-Update-TDL.patch.license
test/api_stability/1.1.1/0002-API-Quoted-strings-and-paths.patch
test/api_stability/1.1.1/0002-API-Quoted-strings-and-paths.patch.license
test/api_stability/1.1.1/0003-NOAPI-Update-copyright.patch
test/api_stability/1.1.1/0003-NOAPI-Update-copyright.patch.license
test/api_stability/1.1.1/0004-INFRA-Update-TDL.patch
test/api_stability/1.1.1/0004-INFRA-Update-TDL.patch.license
test/api_stability/1.1.1/0005-INFRA-Use-seqan3-main-branch.patch
test/api_stability/1.1.1/0005-INFRA-Use-seqan3-main-branch.patch.license
test/api_stability/1.1.1/0006-API-FIX-positional-options-in-CWL-CTD.patch
test/api_stability/1.1.1/0006-API-FIX-positional-options-in-CWL-CTD.patch.license
test/api_stability/1.1.1/0007-API-MISC-Defer-everything-to-parse.patch
test/api_stability/1.1.1/0007-API-MISC-Defer-everything-to-parse.patch.license
test/api_stability/1.1.1/0008-API-MISC-Allow-options-for-subcommands.patch
test/api_stability/1.1.1/0008-API-MISC-Allow-options-for-subcommands.patch.license
test/api_stability/1.1.1/0009-FIX-is_option_set-match-both-long-and-short-ids.patch
test/api_stability/REUSE.toml

[FIX,TEST] API

---

doc/howto/subcommand_parser/index.md
include/sharg/auxiliary.hpp
include/sharg/parser.hpp
test/unit/parser/subcommand_test.cpp

Subparsers do not have any metadata set. 
When you already set metadata for the top-level parser, you need to do so again for the subparser.
This PR makes it so that some metadata is copied to the subparser:
| Metadata | Copied? |
|----------|---------|
| `app_name` | ⛔ |
| `version` | ✅ |
| `short_description` | ❌ |
| `author` | ✅ |
| `email` | ✅ |
| `date` | ✅ |
| `url` | ✅ |
| `short_copyright` | ✅ |
| `long_copyright` | ✅ |
| `citation` | ✅ |
| `man_page_title` | ❌ |
| `man_page_section` | ❌ |
| `description` | ❌ |
| `synopsis` | ❌ |
| `examples` | ❌ |
* `copy_metadata_to_subparser` could also be a member function of `parser_meta_data` for better encapsulation.
* `app_name` is overwritten.
* I don't think it makes sense to copy the other metadata too?
Excerpts of the help page for …

[FEATURE] Copy some metadata to subparsers
