.gitignore
doc/cookbook/basic_arg_parse.out
doc/howto/subcommand_argument_parser/subcommand_arg_parse.out
doc/tutorial/argument_parser/basic_parser_setup.out
doc/tutorial/argument_parser/solution3.out
doc/tutorial/argument_parser/solution4.out
doc/tutorial/argument_parser/solution5.out
doc/tutorial/argument_parser/solution6.out
test/snippet/CMakeLists.txt

Not ignoring `.out` might help to avoid issues in the future :)
relates to #20

[TEST] Enable snippet test for doc

---

README.md

[DOC] Use logo of repo in README

---

include/sharg/detail/version_check.hpp
include/sharg/validators.hpp

The easy part in making sharg independent of seqan3 :shrug:

[MISC] Remove unused includes.

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

[DOC] bug report template

---

include/sharg/argument_parser.hpp
include/sharg/detail/format_parse.hpp

[MISC] Remove dependency of char/predicate.hpp.

---

include/sharg/detail/safe_filesystem_entry.hpp
include/sharg/detail/version_check.hpp
include/sharg/validators.hpp
test/snippet/safe_filesystem_entry.cpp
test/unit/detail/CMakeLists.txt
test/unit/detail/safe_filesystem_entry_test.cpp

Resolves partly #16 
I had to copy tmp_filename.hpp aswell -> follow up PR: #32 .

[MISC] Remove dependency of seqan3::detail::safe_filesystem_entry.

---

include/sharg/detail/format_base.hpp
test/unit/detail/format_help_test.cpp

It's not even less readable I think.

[MISC] Remove dependency on type traits.

---

test/include/sharg/test/file_access.hpp
test/include/sharg/test/tmp_filename.hpp
test/unit/format_parse_validators_test.cpp
test/unit/test/CMakeLists.txt
test/unit/test/file_access_test.cpp
test/unit/test/tmp_filename_test.cpp

Resolves partly #16 
Follow up for #32

[MISC] Remove dependency of seqan3::test::file_access

---

include/sharg/contrib/charconv
include/sharg/contrib/charconv.cpp
include/sharg/contrib/charconv_pre.hpp
include/sharg/detail/format_parse.hpp
include/sharg/detail/version_check.hpp
include/sharg/std/charconv
test/unit/std/CMakeLists.txt
test/unit/std/charconv_float_test.cpp
test/unit/std/charconv_int_test.cpp

I basically copied over everything from seqan and renamed `SEQAN_` to `SHARG_`
Fixes #35

[MISC] Add std charconv module

---

include/sharg/argument_parser.hpp
include/sharg/detail/format_help.hpp
include/sharg/detail/test_accessor.hpp
test/unit/detail/format_help_test.cpp
test/unit/detail/version_check_test.hpp
test/unit/format_parse_validators_test.cpp

[MISC] Remove dependency of seqan3::detail::test_accessor.

---

CHANGELOG.md

[DOC] Update changelog

---

CONTRIBUTING.md

Directly resolves this issue: https://github.com/seqan/sharg-parser/issues/48 which is a part of this larger one: https://github.com/seqan/sharg-parser/issues/20

Adapt the contributions guide for Sharg

---

doc/cookbook/index.md
doc/tutorial/argument_parser/index.md
doc/tutorial/concepts/custom_validator_solution.cpp
doc/tutorial/concepts/custom_validator_solution.out

[DOC] Copy over the cookbook entry about the custom validator

---

.github/workflows/ci_misc.yml
doc/tutorial/argument_parser/index.md
include/sharg/argument_parser.hpp
include/sharg/validators.hpp

[DOC] Update doxygen to 1.9.3 and fix warnings

---

doc/tutorial/argument_parser/index.md
doc/tutorial/argument_parser/small_snippets.cpp
doc/tutorial/argument_parser/solution3.cpp
doc/tutorial/argument_parser/solution4.cpp
doc/tutorial/argument_parser/solution5.cpp
doc/tutorial/argument_parser/solution6.cpp
include/sharg/argument_parser.hpp
include/sharg/detail/format_parse.hpp
include/sharg/exceptions.hpp
test/unit/argument_parser_design_error_test.cpp
test/unit/detail/format_help_test.cpp
test/unit/detail/format_html_test.cpp
test/unit/detail/format_man_test.cpp
test/unit/detail/version_check_test.hpp
test/unit/format_parse_test.cpp

Resolves https://github.com/seqan/sharg-parser/issues/65

[DOC, BUG] Clarify flag default value

---

doc/about/api/index.md

[DOC] Adapt API/ABI stability documentation.

---

CHANGELOG.md
include/sharg/auxiliary.hpp
include/sharg/concept.hpp
include/sharg/detail/format_base.hpp
include/sharg/detail/to_string.hpp
include/sharg/validators.hpp
test/unit/detail/format_help_test.cpp
test/unit/format_parse_test.cpp
test/unit/format_parse_validators_test.cpp

[MISC] Remove seqan3::debug_stream and seqan3::detail::to_string.

---

include/sharg/detail/format_base.hpp
include/sharg/detail/format_parse.hpp

Port of https://github.com/seqan/seqan3/pull/2979/commits/416b6ad9557130864c326bc82f1e6df3b2c31357

[FIX] bogus gcc12 warnings

---

include/sharg/argument_parser.hpp

[DOC] Add POSIX to documentation.

---

build_system/sharg-config.cmake
doc/about/update_notifications/index.md
test/documentation/DoxygenLayout.xml

Copied over from https://github.com/seqan/seqan3/wiki/Update-Notifications
Follow up tracked in #92

[DOC] Add documentation on Update Notifications

---

include/sharg/argument_parser.hpp
include/sharg/detail/version_check.hpp
test/unit/detail/version_check_test.hpp

[DOC] Change link to Update Notification URL.

---

doc/cookbook/index.md
doc/howto/custom_types/index.md
doc/howto/custom_validator/custom_validator_solution1.cpp
doc/howto/custom_validator/index.md
doc/howto/subcommand_argument_parser/index.md
doc/tutorial/argument_parser/index.md
include/sharg/argument_parser.hpp
test/documentation/DoxygenLayout.xml

Validator doc

---

include/sharg/config.hpp
include/sharg/detail/format_base.hpp
include/sharg/parser.hpp
test/unit/detail/format_help_test.cpp
test/unit/detail/format_html_test.cpp
test/unit/detail/format_man_test.cpp
test/unit/parser/parser_design_error_test.cpp

[FEATURE] Add default_message

---

test/documentation/sharg-doxygen.cmake

Part of https://github.com/seqan/sharg-parser/issues/85

[INFRA] Update cppreference doxygen webtags

---

doc/setup/quickstart_cmake/index.md

Part of https://github.com/seqan/sharg-parser/issues/85

[DOC] Update directory structure

---

.github/ISSUE_TEMPLATE/release-checklist.md
test/scripts/link_check.sh

Part of https://github.com/seqan/sharg-parser/issues/85

[MISC] Link check

---

doc/setup/quickstart_cmake/index.md

Part of https://github.com/seqan/sharg-parser/issues/85

[DOC] Update CMake version

---

.github/workflows/api.yml
.github/workflows/ci_linux.yml
.github/workflows/ci_macos.yml
.github/workflows/ci_misc.yml
.github/workflows/documentation.yaml
test/api_stability/CMakeLists.txt
test/api_stability/README.md

[INFRA] Add API test

---

.github/workflows/api.yml

[INFRA] Use environment files

---

test/documentation/sharg_doxygen_cfg.in

See https://github.com/seqan/seqan3/pull/3069

[INFRA] improve Doxygen reproduciblity

---

.github/ISSUE_TEMPLATE/release-checklist.md

[DOC] Update release issue template

---

doc/setup/quickstart_cmake/index.md

Resolves #115
https://gitpod.io/#https://github.com/seqan/sharg-parser/

[DOC] Add gitpod

---

.github/ISSUE_TEMPLATE/release-checklist.md
doc/cookbook/index.md
test/scripts/add_snippets_to_cookbook.sh

Analog to seqan3, this PR adds a script and all snippets of the documentation to the cookbook

[DOC] Add all documentation snippets to the cookbook.

---

.github/workflows/update_cookbook.yml
test/scripts/add_snippets_to_cookbook.sh

Only runs on push, thus merge after CI passes

[INFRA] Add action for updating cookbook

---

CHANGELOG.md
include/sharg/validators.hpp
test/unit/parser/format_parse_validators_test.cpp

[FIX] Segfault in value_list_validator

---

test/api_stability/1.0.0/0001-API-FIX-Print-common-options-at-the-end-of-the-help-.patch
test/api_stability/1.0.0/0002-NOAPI-Update-copyright.patch

Resolves #146 
tested on my fork: https://github.com/eseiler/sharg-parser/actions/runs/4383778843

[FIX] API tests

---

test/api_stability/1.0.0/0001-API-FIX-Print-common-options-at-the-end-of-the-help-.patch
test/api_stability/1.0.0/0002-NOAPI-Update-copyright.patch
test/api_stability/1.0.0/0003-API-FIX-Check-app_name-at-parse.patch
test/api_stability/1.0.0/0004-FIX-API-tdl-support.patch

[FIX,TEST] API tests

---

build_system/sharg-config.cmake
include/sharg/detail/format_parse.hpp
include/sharg/parser.hpp
test/unit/detail/format_help_test.cpp
test/unit/test/tmp_filename_test.cpp

[MISC] clang preparations

---

.github/workflows/ci_misc.yml
include/sharg/validators.hpp

TDL includes are a superset of the no-TDL includes
fixes #221

[INFRA] Do not use TDL in header tests

---

doc/about/update_notifications/index.md
include/sharg/auxiliary.hpp

[DOC] Update version check doc
